name: r-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-clusterprofiler
  - bioconductor-deseq2
  - bioconductor-org.hs.eg.db
  - bioconductor-rhdf5
  - bioconductor-sesame
  - bioconductor-sesamedata
  - bioconductor-tcgabiolinks
  - r-base
